# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Prepare binary for release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p release
        cp .build/release/MachP release/
        cd release
        zip MachP.zip MachP

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: release/MachP.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
